Quick install guide
overwolf/detection-tool pull request #5
Opened 2023-06-07 21:26 UTC by DataDalton

Puts a quick install guide on the main screen in-case anyone is new to GitHub and does not know how to get to releases or operate the tool

2023-06-07 21:32 UTC, DataDalton commented
Changed from worm to virus that is the technical definition

2023-06-07 23:26 UTC, JelllyFace8 commented
?

2023-06-22 06:38 UTC, Timtower requested changes

2023-06-22 06:38 UTC, Timtower commented on README.md
> +In order to quickly install this detection tool, click on the [releases](https://github.com/overwolf/detection-tool) tab on the ride side of the screen
Typo

2023-07-08 20:10 UTC, Prikalel approved these changes
good

2023-07-13 09:55 UTC, DataDalton commented on README.md
> +In order to quickly install this detection tool, click on the [releases](https://github.com/overwolf/detection-tool) tab on the ride side of the screen
Fixed with new commit

2026-01-03 09:17 UTC, DataDalton commented
Gone stale

2026-01-03 09:17 UTC, closed without merging